# Generated by Django 5.0.1 on 2024-02-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_myuser_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
